package core

import (
	"encoding/json"
)

// The 2-party collaborative comparison (paper §VI-A): the same statement as
// SubmitCompareCoZk, but π_cmp is a TurboPlonk/KZG proof generated by the two
// traders alone over malicious-secure SPDZ (no helper node). Each trader
// transports its native final SPDZ value share in an owner-authenticated,
// versioned canonical payload; see SubmitCompareCoZk2pShare. Only Rust
// reconstructs the standard proof.
// Verification runs in the cozk2p Rust staticlib behind a cgo bridge
// (chain built with `-tags cozk2p`; see plonkverify.go).

// settle2pPublic mirrors cozk2p's `SettlePublic` serde layout
// (cozk2p/src/relation.rs): the locked-only comparison statement
// [cmp, locked_a, locked_b, price_a, price_b, a_is_seller]. Field names and order
// must stay in lockstep with the Rust struct.
type settle2pPublic struct {
	Cmp       int    `json:"cmp"`
	LockedA   string `json:"locked_a"`
	LockedB   string `json:"locked_b"`
	PriceA    uint64 `json:"price_a"`
	PriceB    uint64 `json:"price_b"`
	AIsSeller bool   `json:"a_is_seller"`
}

// buildCompare2pPublicJSON rebuilds the canonical `SettlePublic` JSON from
// the request plus on-chain order state: the two locked collateral
// commitments, both orders' collateral prices, and order A's side.
func buildCompare2pPublicJSON(req *CompareRequest, orderA, orderB *Order) ([]byte, error) {
	public := settle2pPublic{
		Cmp:       req.Cmp,
		LockedA:   orderA.LockedCommitment,
		LockedB:   orderB.LockedCommitment,
		PriceA:    collateralPrice(orderA).Uint64(),
		PriceB:    collateralPrice(orderB).Uint64(),
		AIsSeller: orderA.Type == Sell,
	}
	return json.Marshal(&public)
}
