package core

import (
	"encoding/json"
	"fmt"

	"github.com/yu-org/yu/core/context"
)

// ────────────────────── Writing: SettleOrdersCoZk2p ──────────────────────
//
// The 2-party collaborative settlement (docs/cozk2p_design.md): the same
// statement as SettleOrdersCoZk, but the proof is a TurboPlonk/KZG proof
// generated by the two traders alone over malicious-secure SPDZ (no helper
// node). Verification runs in the cozk2p Rust staticlib behind a cgo bridge
// (chain built with `-tags cozk2p`; see plonkverify.go).

// settle2pPublic mirrors cozk2p's `SettlePublic` serde layout (cozk2p/src/
// relation.rs). Commitments are the chain's 64-char big-endian hex strings.
// Field names and order must stay in lockstep with the Rust struct.
type settle2pPublic struct {
	Cmp        int       `json:"cmp"`
	NewOrderA  string    `json:"new_order_a"`
	NewOrderB  string    `json:"new_order_b"`
	NewLockedA string    `json:"new_locked_a"`
	NewLockedB string    `json:"new_locked_b"`
	RecvA      string    `json:"recv_a"`
	RecvB      string    `json:"recv_b"`
	OrderA     string    `json:"order_a"`
	OrderB     string    `json:"order_b"`
	Price      uint64    `json:"price"`
	AIsSeller  bool      `json:"a_is_seller"`
	LockedA    [2]string `json:"locked_a"`
	LockedB    [2]string `json:"locked_b"`
}

// buildSettleCoZk2pPublicJSON rebuilds the canonical `SettlePublic` JSON from
// the request plus on-chain state — the 2-party analogue of
// buildSettleCoZkPublicSignals, carrying the same 15 signals in hex form.
func buildSettleCoZk2pPublicJSON(
	req *CoZkSettleRequest, orderA, orderB *Order, price uint64, aIsSeller bool, acc *Account,
) ([]byte, error) {
	lockedA, err := lockedInputHexesPadded(orderA, acc, 2, lockToken(orderA))
	if err != nil {
		return nil, fmt.Errorf("order A locked inputs: %w", err)
	}
	lockedB, err := lockedInputHexesPadded(orderB, acc, 2, lockToken(orderB))
	if err != nil {
		return nil, fmt.Errorf("order B locked inputs: %w", err)
	}
	public := settle2pPublic{
		Cmp:        req.Cmp,
		NewOrderA:  req.NewOrderACommitment,
		NewOrderB:  req.NewOrderBCommitment,
		NewLockedA: req.NewLockedACommitment,
		NewLockedB: req.NewLockedBCommitment,
		RecvA:      req.RecvACommitment,
		RecvB:      req.RecvBCommitment,
		OrderA:     string(orderA.Amount),
		OrderB:     string(orderB.Amount),
		Price:      price,
		AIsSeller:  aIsSeller,
		LockedA:    [2]string{lockedA[0], lockedA[1]},
		LockedB:    [2]string{lockedB[0], lockedB[1]},
	}
	return json.Marshal(&public)
}

// SettleOrdersCoZk2p settles a matched pair with ONE PLONK proof the two
// traders generated together over 2-party MPC — same preconditions, state
// transition, and event shape as SettleOrdersCoZk; only the proof system and
// the signed message's domain prefix differ.
func (ot *OrderBook) SettleOrdersCoZk2p(ctx *context.WriteContext) error {
	ctx.SetLei(100)

	req := new(CoZkSettleRequest)
	if err := ctx.BindJson(req); err != nil {
		return err
	}
	if err := Validator.Struct(req); err != nil {
		return err
	}

	orderA, orderB, price, aIsSeller, err := ot.loadCoZkMatchedPair(req)
	if err != nil {
		return err
	}

	// Both traders must have signed the settlement message.
	if err := verifyCoZkPairSignatures(req, orderA, orderB, CoZk2pSettleMessage(req)); err != nil {
		return err
	}

	// Verify the jointly generated proof against the reconstructed statement.
	publicJSON, err := buildSettleCoZk2pPublicJSON(req, orderA, orderB, price, aIsSeller, ot.Account)
	if err != nil {
		return fmt.Errorf("building settle_cozk2p public statement: %w", err)
	}
	if err := VerifyPlonkSettle2p(ot.settleCoZk2pVK, req.ZkProof, publicJSON); err != nil {
		return fmt.Errorf("settle_cozk2p proof verification failed: %w", err)
	}

	return ot.applyCoZkSettlement(ctx, req, orderA, orderB, "cozk2p")
}
