package core

import (
	"encoding/json"
	"fmt"

	"github.com/yu-org/yu/core/context"
)

// ────────────────────── Writing: SubmitCompareCoZk2p ──────────────────────
//
// The 2-party collaborative comparison (paper §VI-A): the same statement as
// SubmitCompareCoZk, but π_cmp is a TurboPlonk/KZG proof generated by the
// two traders alone over malicious-secure SPDZ (no helper node).
// Verification runs in the cozk2p Rust staticlib behind a cgo bridge
// (chain built with `-tags cozk2p`; see plonkverify.go).

// settle2pPublic mirrors cozk2p's `SettlePublic` serde layout
// (cozk2p/src/relation.rs): the locked-only comparison statement
// [cmp, locked_a, locked_b, price, a_is_seller]. Field names and order
// must stay in lockstep with the Rust struct.
type settle2pPublic struct {
	Cmp       int    `json:"cmp"`
	LockedA   string `json:"locked_a"`
	LockedB   string `json:"locked_b"`
	Price     uint64 `json:"price"`
	AIsSeller bool   `json:"a_is_seller"`
}

// buildCompare2pPublicJSON rebuilds the canonical `SettlePublic` JSON from
// the request plus on-chain order state: the two locked collateral
// commitments, the pair's execution price, and order A's side.
func buildCompare2pPublicJSON(req *CompareRequest, orderA, orderB *Order) ([]byte, error) {
	public := settle2pPublic{
		Cmp:       req.Cmp,
		LockedA:   orderA.LockedCommitment,
		LockedB:   orderB.LockedCommitment,
		Price:     executionPrice(orderA, orderB),
		AIsSeller: orderA.Type == Sell,
	}
	return json.Marshal(&public)
}

// SubmitCompareCoZk2p records a comparison proven with the 2-party PLONK
// π_cmp — same preconditions and state transition as SubmitCompareCoZk;
// only the proof system and the signed message's domain prefix differ.
func (ot *OrderBook) SubmitCompareCoZk2p(ctx *context.WriteContext) error {
	ctx.SetLei(100)

	req := new(CompareRequest)
	if err := ctx.BindJson(req); err != nil {
		return err
	}
	if err := Validator.Struct(req); err != nil {
		return err
	}

	orderA, orderB, _, err := ot.loadMatchedPair(req.OrderAID, req.OrderBID)
	if err != nil {
		return err
	}
	if err := verifyComparePairSignatures(req, orderA, orderB, CoZk2pCompareMessage(req)); err != nil {
		return err
	}
	publicJSON, err := buildCompare2pPublicJSON(req, orderA, orderB)
	if err != nil {
		return fmt.Errorf("building compare public statement: %w", err)
	}
	if err := VerifyPlonkSettle2p(ot.settleCoZk2pVK, req.ZkProof, publicJSON); err != nil {
		return fmt.Errorf("compare proof verification failed: %w", err)
	}
	return ot.applyCompareResult(ctx, req)
}
