//! Headless end-to-end integration test AND benchmark of the desktop app's
//! REAL 2-party collaborative-ZK settlement on the note model, driven
//! against a live `invisibook` chain with the real `settle2p_session`
//! prover. No webkit, no dioxus-desktop: it links only the settle module,
//! the order-preparation path, and the shared chain library.
//!
//! Covered end to end (with per-step wall-clock timing, printed as a
//! summary table):
//!
//! 1. SendOrder: real send_order Groth16 proofs spending genesis pool
//!    notes (Alice sells 2 ETH @ 3, Bob buys 1 ETH @ 3), then matching.
//! 2. Collaborative compare (subprocess, PLONK verification ON on chain),
//!    with the F1 two-phase ordering: the app lands SubmitCompareCoZk2p
//!    and confirms BOTH orders Settling before the subprocess reveals.
//! 3. Each side's own settle proof, the in-fabric settle-leg exchange,
//!    and the ATOMIC SettlePair (F2) — Bob's order Done, Alice relisted
//!    in place with a 1-ETH remainder, both payout notes minted together.
//!
//! Ignored by default: the two collaborative provers together need ~15 GB
//! of RAM. Build the prerequisites, then run explicitly:
//!
//! ```text
//! make build-chain-cozk2p build-settle2p
//! cd app && cargo test -p invisibook-ui settle_e2e -- --ignored --nocapture
//! ```

#![cfg(not(target_os = "android"))]

use std::{
    fs,
    path::{Path, PathBuf},
    process::{Child, Command},
    sync::Arc,
    time::{Duration, Instant},
};

use invisibook_lib::{
    chain::ChainClient,
    note::{asset_id, fr_from_be_bytes, note_commit, note_fr_to_hex, npk_from_sk},
    note_store::{NOTE_UNSPENT, NoteRecord},
    order_store::OrderOpening,
    types::{Order, OrderStatus, TradeType},
};
use invisibook_ui::{
    components::trade_form::prepare_order,
    settle::{SettleDeps, SettleOutcome, run_settle},
};

// ─────────────────────────── Fixed parameters ───────────────────────────

/// Alice's ed25519 seed (hex, m/44'/60'/0'/0'/0'), matching the Go e2e.
const ALICE_SEED_HEX: &str = "0728a1a2b488fdfe677ebe6de2558f251d7263f311bc0a57cd02b32f69878c5a";
/// Bob's ed25519 seed (hex, m/44'/60'/0'/0'/0'), matching the Go e2e.
const BOB_SEED_HEX: &str = "4e578ced277a96ec9507366a159f9ce5b70789bbe8f934d2bc8ef43c9c2bca77";

const HTTP_URL: &str = "http://localhost:7999";
const WS_URL: &str = "ws://localhost:8999";
const CHAIN_ID: u64 = 1926;

const TOKEN1: &str = "ETH";
const TOKEN2: &str = "USDT";
const PRICE: u64 = 3;

// ─────────────────────────────── Helpers ────────────────────────────────

/// Decode a 64-char hex string into a 32-byte ed25519 seed.
/// `hex_str` must decode to exactly 32 bytes.
fn seed_from_hex(hex_str: &str) -> [u8; 32] {
    let bytes = hex::decode(hex_str).expect("seed must be valid hex");
    let mut seed = [0u8; 32];
    seed.copy_from_slice(&bytes);
    seed
}

/// Absolute repo root, two levels up from this crate's manifest dir (`app/ui`).
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root resolves")
}

/// Best-effort kill of any process holding the chain's ports before a run.
fn kill_chain_ports() {
    let _ = Command::new("bash")
        .arg("-c")
        .arg("lsof -ti:7999 -ti:8999 -ti:8887 | xargs kill -9 2>/dev/null")
        .status();
}

/// Owns the spawned chain process; kills and reaps it on drop.
struct ChainGuard {
    child: Child,
}

impl Drop for ChainGuard {
    /// Kill the chain when the test's scope ends (pass or panic).
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// Render the genesis chain config: cozk2p PLONK verification ON, plus the
/// two genesis pool notes (leaf 0 = Alice's ETH note, leaf 1 = Bob's USDT
/// note) whose openings the local wallets hold.
fn render_config(alice_cm: &str, bob_cm: &str) -> String {
    format!(
        r#"# Generated by settle_e2e — do not commit.
[orderbook]
db_path = "data/orders.db"
settle_cozk2p_vk_path = "vk/settle_cozk2p_vk.bin"
# Explicit dev opt-out: the Groth16 settle VKs are not configured here.
require_proofs = false

[account]
db_path = "data/accounts.db"
require_proofs = false

[[account.genesis_note]]
cm   = "{alice_cm}"
memo = "alice 2 ETH"

[[account.genesis_note]]
cm   = "{bob_cm}"
memo = "bob 3 USDT"
"#
    )
}

/// Poll the chain for a single order by id until `pred` holds or the attempt
/// budget (2 s apart) is exhausted. Returns the matching order, or `None` on
/// timeout. `order_id` must be a full order id.
async fn poll_order<F>(
    client: &ChainClient,
    order_id: &str,
    attempts: u32,
    pred: F,
) -> Option<Order>
where
    F: Fn(&Order) -> bool,
{
    for _ in 0..attempts {
        tokio::time::sleep(Duration::from_secs(2)).await;
        if let Ok(orders) = client
            .query_orders(
                Some(order_id.to_string()),
                None,
                None,
                None,
                None,
                Some(1),
                Some(0),
            )
            .await
        {
            if let Some(order) = orders.into_iter().find(|o| o.id == order_id) {
                if pred(&order) {
                    return Some(order);
                }
            }
        }
    }
    None
}

/// One wallet-side genesis note: full opening + the NoteRecord at its leaf.
fn genesis_note(sk_byte: u8, r_byte: u8, token: &str, amount: u64, leaf: u64) -> NoteRecord {
    let sk = [sk_byte; 32];
    let r = [r_byte; 32];
    let cm = note_commit(
        npk_from_sk(fr_from_be_bytes(&sk)),
        asset_id(token).expect("token"),
        amount,
        fr_from_be_bytes(&r),
    );
    NoteRecord {
        cm: note_fr_to_hex(&cm),
        token: token.into(),
        amount,
        r: hex::encode(r),
        key_index: 0,
        sk: hex::encode(sk),
        leaf_index: leaf,
        status: NOTE_UNSPENT,
        nf: String::new(),
        pending_order: String::new(),
    }
}

/// Prove + submit one order through the production path (`prepare_order` →
/// `ChainClient::send_order`), returning (order_id, opening, prove_ms,
/// submit-to-Pending ms).
async fn place_order(
    client: &Arc<ChainClient>,
    note: &NoteRecord,
    trade_type: TradeType,
    q: u64,
) -> (String, OrderOpening, f64, f64) {
    let lock_token = if trade_type == TradeType::Sell {
        TOKEN1
    } else {
        TOKEN2
    };
    let tree = client.fetch_note_tree().await.expect("fetch note tree");
    let t = Instant::now();
    let prepared = prepare_order(
        CHAIN_ID,
        &tree,
        std::slice::from_ref(note),
        lock_token,
        (TOKEN1.into(), TOKEN2.into()),
        trade_type,
        PRICE,
        q,
        0, // fee 0: the genesis notes back the collateral exactly
    )
    .expect("prepare_order");
    let prove_ms = t.elapsed().as_secs_f64() * 1e3;

    let order_id = prepared.params.id.clone();
    let t = Instant::now();
    client
        .send_order(prepared.params)
        .await
        .expect("send_order");
    // A taker order can match in its landing block, so Matched counts as
    // landed too.
    poll_order(client, &order_id, 15, |o| {
        o.status == OrderStatus::Pending || o.status == OrderStatus::Matched
    })
    .await
    .expect("order landed on chain");
    let land_ms = t.elapsed().as_secs_f64() * 1e3;
    (order_id, prepared.opening, prove_ms, land_ms)
}

/// Pool head (leaf count) for cross-step accounting.
async fn leaf_count(client: &ChainClient) -> u64 {
    client.get_pool_info().await.expect("pool info").leaf_count
}

// ──────────────────────────────── Test ──────────────────────────────────

/// Full-depth 2-party co-zk settlement over a live chain and two real
/// `settle2p_session` provers, note model + two-phase orchestration +
/// atomic SettlePair. Both traders' `run_settle` run concurrently; the
/// cross-quantity match drives the relist path (Bob Done, Alice relisted).
#[tokio::test(flavor = "multi_thread")]
#[ignore = "needs the chain + settle2p_session prover and ~15 GB RAM; run with --ignored"]
async fn settle_e2e_relist() {
    let root = repo_root();
    let chain_dir = root.join("chain");
    let chain_bin = chain_dir.join("invisibook");
    let prover_bin = root.join("cozk2p/target/release/settle2p_session");

    // ── Skip-guard: no binaries, no test (skip, don't fail) ──
    if !chain_bin.exists() || !prover_bin.exists() {
        eprintln!(
            "SKIP settle_e2e_relist: missing prerequisite binary.\n  \
             chain:  {} (exists: {})\n  prover: {} (exists: {})\n  \
             build with `make build-chain-cozk2p` and `make build-settle2p`, then run with --ignored",
            chain_bin.display(),
            chain_bin.exists(),
            prover_bin.display(),
            prover_bin.exists(),
        );
        return;
    }

    // ── Two ChainClients (Alice, Bob) from the known seeds ──
    let alice = Arc::new(ChainClient::new(
        HTTP_URL,
        WS_URL,
        seed_from_hex(ALICE_SEED_HEX),
        CHAIN_ID,
    ));
    let bob = Arc::new(ChainClient::new(
        HTTP_URL,
        WS_URL,
        seed_from_hex(BOB_SEED_HEX),
        CHAIN_ID,
    ));

    // ── Genesis pool notes: Alice holds 2 ETH (backs her 2-ETH sell
    //    exactly), Bob holds 3 USDT (backs his 1-ETH buy at price 3). ──
    let alice_note = genesis_note(0x42, 0x33, TOKEN1, 2, 0);
    let bob_note = genesis_note(0x43, 0x34, TOKEN2, 3, 1);

    // ── Write the generated config and start a fresh chain on it ──
    let config = render_config(&alice_note.cm, &bob_note.cm);
    let pid = std::process::id();
    let cfg_path = std::env::temp_dir().join(format!("settle_e2e_core_{pid}.toml"));
    fs::write(&cfg_path, config).expect("write chain config");

    kill_chain_ports();
    std::thread::sleep(Duration::from_secs(1));
    let _ = fs::remove_dir_all(chain_dir.join("data"));
    let child = Command::new(&chain_bin)
        .arg("--core-config")
        .arg(&cfg_path)
        .current_dir(&chain_dir)
        .spawn()
        .expect("spawn chain");
    let _chain = ChainGuard { child };
    // Wait for the first block.
    tokio::time::sleep(Duration::from_secs(6)).await;
    assert_eq!(leaf_count(&alice).await, 2, "genesis notes must be seeded");

    // ── Step 1: SendOrder both sides (real send_order proofs). Alice
    //    first so her sell is in an earlier block → deterministic maker. ──
    let (alice_order_id, alice_opening, alice_prove_ms, alice_land_ms) =
        place_order(&alice, &alice_note, TradeType::Sell, 2).await;
    let (bob_order_id, bob_opening, bob_prove_ms, bob_land_ms) =
        place_order(&bob, &bob_note, TradeType::Buy, 1).await;

    // ── Step 2: both orders reach Matched ──
    let t_match = Instant::now();
    let alice_matched = poll_order(&alice, &alice_order_id, 20, |o| {
        o.status == OrderStatus::Matched && o.match_order.is_some()
    })
    .await
    .expect("sell order Matched");
    let bob_matched = poll_order(&bob, &bob_order_id, 20, |o| {
        o.status == OrderStatus::Matched && o.match_order.is_some()
    })
    .await
    .expect("buy order Matched");
    let match_ms = t_match.elapsed().as_secs_f64() * 1e3;
    // Deterministic role assignment relies on the sell being the maker.
    assert!(
        alice_matched.block_height < bob_matched.block_height,
        "sell must be placed in an earlier block than the buy (maker = seller)"
    );
    let pool_before_settle = leaf_count(&alice).await;

    // ── Settle deps: shared prover + keys dir, per-party session dir ──
    let keys_dir = root.join("cozk2p/target/settle2p-keys");
    fs::create_dir_all(&keys_dir).expect("create keys dir");
    let sessions_root = std::env::temp_dir().join(format!("settle_e2e_sessions_{pid}"));
    let alice_deps = SettleDeps {
        bin: prover_bin.clone(),
        keys_dir: keys_dir.clone(),
        sessions_dir: sessions_root.join("alice"),
        note_seed: seed_from_hex(ALICE_SEED_HEX),
    };
    let bob_deps = SettleDeps {
        bin: prover_bin.clone(),
        keys_dir: keys_dir.clone(),
        sessions_dir: sessions_root.join("bob"),
        note_seed: seed_from_hex(BOB_SEED_HEX),
    };

    // Warm the proving-key cache once so the two concurrent provers don't race
    // to generate it (cold keygen ~1 min).
    let warmed = Command::new(&prover_bin)
        .arg("--warm-keys")
        .arg("--keys-dir")
        .arg(&keys_dir)
        .status()
        .expect("run --warm-keys");
    assert!(warmed.success(), "warm-keys must succeed");

    // ── Step 3: run BOTH parties' run_settle concurrently. This drives the
    //    complete hardened flow: MPC compare → compare_ready → on-chain
    //    SubmitCompareCoZk2p + Settling confirm (F1 gate) → reveal → own
    //    settle proofs → in-fabric leg exchange → atomic SettlePair (F2). ──
    let t_settle = Instant::now();
    let alice_fut = run_settle(
        &alice,
        &alice_matched,
        &bob_matched,
        &alice_opening,
        &alice_deps,
        |s| eprintln!("[alice] {s}"),
    );
    let bob_fut = run_settle(
        &bob,
        &bob_matched,
        &alice_matched,
        &bob_opening,
        &bob_deps,
        |s| eprintln!("[bob] {s}"),
    );
    let (alice_res, bob_res) = tokio::join!(alice_fut, bob_fut);
    let settle_ms = t_settle.elapsed().as_secs_f64() * 1e3;

    let alice_outcome: SettleOutcome = alice_res.expect("alice run_settle must succeed");
    let bob_outcome: SettleOutcome = bob_res.expect("bob run_settle must succeed");

    // ── Outcome amounts (precise) ──
    // cmp = sign(order_a - order_b) = sign(2 - 1) = 1, seen by both parties.
    assert_eq!(alice_outcome.cmp, 1, "cmp must be sign(2 - 1) = 1");
    assert_eq!(bob_outcome.cmp, 1);

    // Alice (seller) receives USDT = fill * price = 1 * 3 = 3.
    assert_eq!(alice_outcome.recv.token, TOKEN2);
    assert_eq!(alice_outcome.recv.amount, 3);
    // Alice is the larger side: she survives with a 1-ETH remainder whose
    // residual opening replaces her order opening.
    let rem = alice_outcome
        .remainder
        .as_ref()
        .expect("alice must have a remainder");
    assert_eq!(rem.order_amount, 1, "relisted order quantity = 1 ETH");
    assert_eq!(rem.locked_amount, 1, "2 locked - 1 filled = 1 ETH residual");

    // Bob (buyer) receives ETH = fill = 1, and fully fills (no remainder).
    assert_eq!(bob_outcome.recv.token, TOKEN1);
    assert_eq!(bob_outcome.recv.amount, 1);
    assert!(bob_outcome.remainder.is_none(), "bob fully fills");

    // ── On-chain end state ──
    // Bob's order is Done.
    let bob_final = poll_order(&bob, &bob_order_id, 10, |o| o.status == OrderStatus::Done)
        .await
        .expect("buy order must be Done");
    assert_eq!(bob_final.status, OrderStatus::Done);

    // Alice's order is relisted in place: SAME id, still on the book, its
    // single collateral commitment rewritten to the residual (locked-only
    // model: there is no quantity commitment).
    let alice_final = poll_order(&alice, &alice_order_id, 10, |o| {
        o.status == OrderStatus::Pending
    })
    .await
    .expect("sell order must be relisted Pending");
    assert_eq!(alice_final.id, alice_order_id, "relisted under the same id");
    assert_ne!(
        alice_final.locked_commitment, alice_matched.locked_commitment,
        "collateral commitment must be rewritten to the residual commitment"
    );

    // ── Payout NOTES exist in the pool tree; the atomic SettlePair minted
    //    exactly the two of them (F2: both or nothing). ──
    assert!(
        bob.get_note_by_cm(&bob_outcome.recv.cm)
            .await
            .expect("bob note lookup")
            >= 0,
        "bob's payout note must be in the pool tree"
    );
    assert!(
        alice
            .get_note_by_cm(&alice_outcome.recv.cm)
            .await
            .expect("alice note lookup")
            >= 0,
        "alice's payout note must be in the pool tree"
    );
    assert_eq!(
        leaf_count(&alice).await,
        pool_before_settle + 2,
        "settlement must mint exactly the two payout notes"
    );

    // ── Per-step timing summary (session-internal phases from the
    //    subprocess stats.json files, host waits reported separately) ──
    #[derive(serde::Deserialize, Default)]
    struct Stats {
        #[serde(default)]
        build_ms: f64,
        #[serde(default)]
        prove_ms: f64,
        #[serde(default)]
        open_ms: f64,
        #[serde(default)]
        compare_onchain_wait_ms: f64,
        #[serde(default)]
        leg_exchange_ms: f64,
        #[serde(default)]
        total_ms: f64,
    }
    let read_stats = |dir: &Path| -> Stats {
        fs::read_to_string(dir.join("stats.json"))
            .ok()
            .and_then(|s| serde_json::from_str(&s).ok())
            .unwrap_or_default()
    };
    let sa = read_stats(&alice_outcome.session_dir);
    let sb = read_stats(&bob_outcome.session_dir);

    eprintln!("\n════════ settle_e2e wall-clock summary (ms) ════════");
    eprintln!("{:<44} {:>10} {:>10}", "step", "alice", "bob");
    let row = |name: &str, a: f64, b: f64| eprintln!("{name:<44} {a:>10.0} {b:>10.0}");
    row(
        "send_order prove (rapidsnark)",
        alice_prove_ms,
        bob_prove_ms,
    );
    row("send_order submit → Pending", alice_land_ms, bob_land_ms);
    row("match wait (both Matched)", match_ms, match_ms);
    row("π_cmp circuit build (MPC)", sa.build_ms, sb.build_ms);
    row("π_cmp collaborative prove", sa.prove_ms, sb.prove_ms);
    row("π_cmp proof open", sa.open_ms, sb.open_ms);
    row(
        "compare on-chain wait (host, NOT crypto)",
        sa.compare_onchain_wait_ms,
        sb.compare_onchain_wait_ms,
    );
    row(
        "settle-leg exchange (incl. peer prove wait)",
        sa.leg_exchange_ms,
        sb.leg_exchange_ms,
    );
    row("session subprocess total", sa.total_ms, sb.total_ms);
    row("run_settle total (both, concurrent)", settle_ms, settle_ms);
    eprintln!("════════════════════════════════════════════════════\n");

    // Scratch cleanup (the chain process is killed by ChainGuard on drop).
    let _ = fs::remove_dir_all(&alice_outcome.session_dir);
    let _ = fs::remove_dir_all(&bob_outcome.session_dir);
    let _ = fs::remove_dir_all(&sessions_root);
    let _ = fs::remove_file(&cfg_path);
}
