//! Headless end-to-end integration test of the desktop app's REAL 2-party
//! collaborative-ZK settlement (`invisibook_ui::settle::run_settle`), driven
//! against a live `invisibook` chain with the real `settle2p_session` prover.
//! No webkit, no dioxus-desktop: it links only the settle module and the
//! shared chain library.
//!
//! Ignored by default: the two collaborative provers together need ~15 GB of
//! RAM. Build the prerequisites, then run explicitly:
//!
//! ```text
//! make build-chain-cozk2p build-settle2p
//! cd app && cargo test -p invisibook-ui settle_e2e -- --ignored --nocapture
//! ```
//!
//! The trade exercises the RELIST path: Alice SELLS 2 ETH @ price 3, Bob BUYS
//! 1 ETH @ price 3. Different quantities ⇒ cmp = 1 ⇒ Bob fully fills (order
//! Done) while Alice survives with a 1-ETH remainder that the chain relists
//! in place under the same order id.

#![cfg(not(target_os = "android"))]

use std::{
    fs,
    path::{Path, PathBuf},
    process::{Child, Command},
    sync::Arc,
    time::Duration,
};

use invisibook_lib::{
    cash_store::CashRecord,
    chain::ChainClient,
    orderbook,
    types::{CASH_ACTIVE, CASH_LOCKED, Order, OrderStatus, TradePair, TradeType},
};
use invisibook_ui::settle::{SettleDeps, SettleOutcome, run_settle};

// ─────────────────────────── Fixed parameters ───────────────────────────

/// Alice's ed25519 seed (hex, m/44'/60'/0'/0'/0'), matching the Go e2e.
const ALICE_SEED_HEX: &str = "0728a1a2b488fdfe677ebe6de2558f251d7263f311bc0a57cd02b32f69878c5a";
/// Bob's ed25519 seed (hex, m/44'/60'/0'/0'/0'), matching the Go e2e.
const BOB_SEED_HEX: &str = "4e578ced277a96ec9507366a159f9ce5b70789bbe8f934d2bc8ef43c9c2bca77";

const HTTP_URL: &str = "http://localhost:7999";
const WS_URL: &str = "ws://localhost:8999";
const CHAIN_ID: u64 = 1926;

const TOKEN1: &str = "ETH";
const TOKEN2: &str = "USDT";
const PRICE: u64 = 3;

// ─────────────────────────────── Helpers ────────────────────────────────

/// Decode a 64-char hex string into a 32-byte ed25519 seed.
/// `hex_str` must decode to exactly 32 bytes.
fn seed_from_hex(hex_str: &str) -> [u8; 32] {
    let bytes = hex::decode(hex_str).expect("seed must be valid hex");
    let mut seed = [0u8; 32];
    seed.copy_from_slice(&bytes);
    seed
}

/// Absolute repo root, two levels up from this crate's manifest dir (`app/ui`).
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root resolves")
}

/// Best-effort kill of any process holding the chain's ports before a run.
fn kill_chain_ports() {
    let _ = Command::new("bash")
        .arg("-c")
        .arg("lsof -ti:7999 -ti:8999 -ti:8887 | xargs kill -9 2>/dev/null")
        .status();
}

/// Owns the spawned chain process; kills and reaps it on drop.
struct ChainGuard {
    child: Child,
}

impl Drop for ChainGuard {
    /// Kill the chain when the test's scope ends (pass or panic).
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// Render the genesis chain config: cozk2p PLONK verification ON, plus one
/// locked-collateral genesis cash per trader whose commitment the trader's
/// local `CashRecord` opens. `*_commitment` must be the 64-hex Poseidon
/// commitment (not plaintext); `*_cash_id` its content-addressed id.
#[allow(clippy::too_many_arguments)]
fn render_config(
    alice_pubkey: &str,
    alice_eth_cash_id: &str,
    alice_eth_commitment: &str,
    bob_pubkey: &str,
    bob_usdt_cash_id: &str,
    bob_usdt_commitment: &str,
) -> String {
    format!(
        r#"# Generated by settle_e2e_relist — do not commit.
[orderbook]
db_path = "data/orders.db"
settle_cozk2p_vk_path = "vk/settle_cozk2p_vk.bin"

[account]
db_path = "data/accounts.db"

[[account.genesis_cash]]
id     = "{alice_eth_cash_id}"
pubkey = "{alice_pubkey}"
token  = "ETH"
amount = "{alice_eth_commitment}"

[[account.genesis_cash]]
id     = "{bob_usdt_cash_id}"
pubkey = "{bob_pubkey}"
token  = "USDT"
amount = "{bob_usdt_commitment}"
"#
    )
}

/// Poll the chain for a single order by id until `pred` holds or the attempt
/// budget (2 s apart) is exhausted. Returns the matching order, or `None` on
/// timeout. `order_id` must be a full order id.
async fn poll_order<F>(
    client: &ChainClient,
    order_id: &str,
    attempts: u32,
    pred: F,
) -> Option<Order>
where
    F: Fn(&Order) -> bool,
{
    for _ in 0..attempts {
        tokio::time::sleep(Duration::from_secs(2)).await;
        if let Ok(orders) = client
            .query_orders(
                Some(order_id.to_string()),
                None,
                None,
                None,
                None,
                Some(1),
                Some(0),
            )
            .await
        {
            if let Some(order) = orders.into_iter().find(|o| o.id == order_id) {
                if pred(&order) {
                    return Some(order);
                }
            }
        }
    }
    None
}

// ──────────────────────────────── Test ──────────────────────────────────

/// Full-depth 2-party co-zk settlement over a live chain and two real
/// `settle2p_session` provers. Both traders' `run_settle` run concurrently;
/// the cross-quantity match drives the relist path (Bob Done, Alice relisted).
#[tokio::test(flavor = "multi_thread")]
#[ignore = "needs the chain + settle2p_session prover and ~15 GB RAM; run with --ignored"]
async fn settle_e2e_relist() {
    let root = repo_root();
    let chain_dir = root.join("chain");
    let chain_bin = chain_dir.join("invisibook");
    let prover_bin = root.join("cozk2p/target/release/settle2p_session");

    // ── Skip-guard: no binaries, no test (skip, don't fail) ──
    if !chain_bin.exists() || !prover_bin.exists() {
        eprintln!(
            "SKIP settle_e2e_relist: missing prerequisite binary.\n  \
             chain:  {} (exists: {})\n  prover: {} (exists: {})\n  \
             build with `make build-chain-cozk2p` and `make build-settle2p`, then run with --ignored",
            chain_bin.display(),
            chain_bin.exists(),
            prover_bin.display(),
            prover_bin.exists(),
        );
        return;
    }

    // ── Two ChainClients (Alice, Bob) from the known seeds ──
    let alice = Arc::new(ChainClient::new(
        HTTP_URL,
        WS_URL,
        seed_from_hex(ALICE_SEED_HEX),
        CHAIN_ID,
    ));
    let bob = Arc::new(ChainClient::new(
        HTTP_URL,
        WS_URL,
        seed_from_hex(BOB_SEED_HEX),
        CHAIN_ID,
    ));
    let alice_pubkey = alice.pubkey_hex().to_string();
    let bob_pubkey = bob.pubkey_hex().to_string();

    // ── Genesis collateral commitments (opened by the local CashRecords) ──
    // Alice sells 2 ETH: BOTH her locked ETH cash and her sell order commit to
    // (amount = 2, r_eth) — the genesis-sale convention where order.amount
    // reuses the cash's own commitment. The order witness is still carried
    // explicitly on the CashRecord (build_my_private requires it).
    let (alice_eth_commitment, _, r_eth) = orderbook::encrypt_amount_with_info("2");
    let alice_eth_cash_id =
        orderbook::compute_cash_id(&alice_pubkey, TOKEN1, &alice_eth_commitment);

    // Bob buys 1 ETH @ 3, locking 3 USDT. His USDT cash commits to
    // (amount = 3, r_usdt); his BUY order commits to the token1 quantity
    // (amount = 1) under a FRESH order random — mirrors trade_form's buy path.
    let (bob_usdt_commitment, _, r_usdt) = orderbook::encrypt_amount_with_info("3");
    let bob_usdt_cash_id = orderbook::compute_cash_id(&bob_pubkey, TOKEN2, &bob_usdt_commitment);
    let (bob_order_commitment, _, r_bob_order) = orderbook::encrypt_amount_with_info("1");

    // Order ids are the SHA-256 of their input cash ids.
    let alice_order_id = orderbook::compute_order_id(&[alice_eth_cash_id.clone()]);
    let bob_order_id = orderbook::compute_order_id(&[bob_usdt_cash_id.clone()]);

    // ── Write the generated config and start a fresh chain on it ──
    let config = render_config(
        &alice_pubkey,
        &alice_eth_cash_id,
        &alice_eth_commitment,
        &bob_pubkey,
        &bob_usdt_cash_id,
        &bob_usdt_commitment,
    );
    let pid = std::process::id();
    let cfg_path = std::env::temp_dir().join(format!("settle_e2e_core_{pid}.toml"));
    fs::write(&cfg_path, config).expect("write chain config");

    kill_chain_ports();
    std::thread::sleep(Duration::from_secs(1));
    let _ = fs::remove_dir_all(chain_dir.join("data"));
    let child = Command::new(&chain_bin)
        .arg("--core-config")
        .arg(&cfg_path)
        .current_dir(&chain_dir)
        .spawn()
        .expect("spawn chain");
    let _chain = ChainGuard { child };
    // Wait for the first block.
    tokio::time::sleep(Duration::from_secs(6)).await;

    // ── Alice SELLS 2 ETH @ 3 (no split: her genesis cash is locked in place;
    //    order.amount == the locked-cash commitment) ──
    let alice_order = Order {
        id: alice_order_id.clone(),
        trade_type: TradeType::Sell,
        subject: TradePair {
            token1: TOKEN1.into(),
            token2: TOKEN2.into(),
        },
        price: Some(PRICE),
        amount: alice_eth_commitment.clone(),
        pubkey: alice_pubkey.clone(),
        input_cash_ids: vec![alice_eth_cash_id.clone()],
        handling_fee: vec!["0".into()],
        block_height: 0,
        status: OrderStatus::Pending,
        match_order: None,
        is_smaller: false,
    };
    alice
        .send_order(&alice_order, None, None, None)
        .await
        .expect("send sell order");
    // Confirm the sell lands (Pending) BEFORE placing the buy, so the sell is
    // in an earlier block → deterministic maker (Alice = trader-a = seller).
    poll_order(&alice, &alice_order_id, 15, |o| {
        o.status == OrderStatus::Pending
    })
    .await
    .expect("sell order confirmed Pending");

    // ── Bob BUYS 1 ETH @ 3 → matches Alice's sell (no split: 3 USDT exact) ──
    let bob_order = Order {
        id: bob_order_id.clone(),
        trade_type: TradeType::Buy,
        subject: TradePair {
            token1: TOKEN1.into(),
            token2: TOKEN2.into(),
        },
        price: Some(PRICE),
        amount: bob_order_commitment.clone(),
        pubkey: bob_pubkey.clone(),
        input_cash_ids: vec![bob_usdt_cash_id.clone()],
        handling_fee: vec!["0".into()],
        block_height: 0,
        status: OrderStatus::Pending,
        match_order: None,
        is_smaller: false,
    };
    bob.send_order(&bob_order, None, None, None)
        .await
        .expect("send buy order");

    // ── Wait for both orders to reach Matched ──
    let alice_matched = poll_order(&alice, &alice_order_id, 20, |o| {
        o.status == OrderStatus::Matched && o.match_order.is_some()
    })
    .await
    .expect("sell order Matched");
    let bob_matched = poll_order(&bob, &bob_order_id, 20, |o| {
        o.status == OrderStatus::Matched && o.match_order.is_some()
    })
    .await
    .expect("buy order Matched");
    // Deterministic role assignment relies on the sell being the maker.
    assert!(
        alice_matched.block_height < bob_matched.block_height,
        "sell must be placed in an earlier block than the buy (maker = seller)"
    );

    // ── Each trader's local CashRecords (must open the on-chain commitments) ──
    let alice_records = vec![CashRecord {
        cash_id: alice_eth_cash_id.clone(),
        token: TOKEN1.into(),
        amount: 2,
        random: r_eth.clone(),
        status: CASH_LOCKED,
        // Sell: order.amount reuses the cash's own (amount, random) here, but
        // the witness must still be carried explicitly.
        order_amount: Some(2),
        order_random: Some(r_eth),
    }];
    let bob_records = vec![CashRecord {
        cash_id: bob_usdt_cash_id.clone(),
        token: TOKEN2.into(),
        amount: 3,
        random: r_usdt,
        status: CASH_LOCKED,
        // Buy: order.amount commits the token1 qty (1) under its own random.
        order_amount: Some(1),
        order_random: Some(r_bob_order),
    }];

    // ── Settle deps: shared prover + keys dir, per-party session dir ──
    let keys_dir = root.join("cozk2p/target/settle2p-keys");
    fs::create_dir_all(&keys_dir).expect("create keys dir");
    let sessions_root = std::env::temp_dir().join(format!("settle_e2e_sessions_{pid}"));
    let alice_deps = SettleDeps {
        bin: prover_bin.clone(),
        keys_dir: keys_dir.clone(),
        sessions_dir: sessions_root.join("alice"),
        note_seed: seed_from_hex(ALICE_SEED_HEX),
    };
    let bob_deps = SettleDeps {
        bin: prover_bin.clone(),
        keys_dir: keys_dir.clone(),
        sessions_dir: sessions_root.join("bob"),
        note_seed: seed_from_hex(BOB_SEED_HEX),
    };

    // Warm the proving-key cache once so the two concurrent provers don't race
    // to generate it (cold keygen ~1 min).
    let warmed = Command::new(&prover_bin)
        .arg("--warm-keys")
        .arg("--keys-dir")
        .arg(&keys_dir)
        .status()
        .expect("run --warm-keys");
    assert!(warmed.success(), "warm-keys must succeed");

    // ── Run BOTH parties' run_settle concurrently ──
    let alice_fut = run_settle(
        &alice,
        &alice_matched,
        &bob_matched,
        &alice_records,
        &alice_deps,
        |s| eprintln!("[alice] {s}"),
    );
    let bob_fut = run_settle(
        &bob,
        &bob_matched,
        &alice_matched,
        &bob_records,
        &bob_deps,
        |s| eprintln!("[bob] {s}"),
    );
    let (alice_res, bob_res) = tokio::join!(alice_fut, bob_fut);

    let alice_outcome: SettleOutcome = alice_res.expect("alice run_settle must succeed");
    let bob_outcome: SettleOutcome = bob_res.expect("bob run_settle must succeed");

    // ── Outcome amounts (precise) ──
    // cmp = sign(order_a - order_b) = sign(2 - 1) = 1, seen by both parties.
    assert_eq!(alice_outcome.cmp, 1, "cmp must be sign(2 - 1) = 1");
    assert_eq!(bob_outcome.cmp, 1);

    // Alice (seller) receives USDT = fill * price = 1 * 3 = 3.
    assert_eq!(alice_outcome.recv.token, TOKEN2);
    assert_eq!(alice_outcome.recv.amount, 3);
    // Alice is the larger side: she survives with a 1-ETH remainder.
    let rem = alice_outcome
        .remainder
        .as_ref()
        .expect("alice must have a remainder");
    assert_eq!(rem.locked.token, TOKEN1);
    assert_eq!(rem.locked.amount, 1, "2 sold - 1 filled = 1 ETH remainder");
    assert_eq!(rem.order_amount, 1, "relisted order quantity = 1 ETH");

    // Bob (buyer) receives ETH = fill = 1, and fully fills (no remainder).
    assert_eq!(bob_outcome.recv.token, TOKEN1);
    assert_eq!(bob_outcome.recv.amount, 1);
    assert!(bob_outcome.remainder.is_none(), "bob fully fills");

    // ── On-chain end state ──
    // Bob's order is Done.
    let bob_final = poll_order(&bob, &bob_order_id, 10, |o| o.status == OrderStatus::Done)
        .await
        .expect("buy order must be Done");
    assert_eq!(bob_final.status, OrderStatus::Done);

    // Alice's order is relisted in place: SAME id, still on the book, and its
    // commitment rewritten to the remainder's new order commitment. (run_settle
    // already required `amount == new_order_a` in its confirm step before
    // returning Ok; here we independently witness the relist — id survives and
    // the commitment moved off the original.)
    let alice_final = poll_order(&alice, &alice_order_id, 10, |o| {
        o.status == OrderStatus::Pending
    })
    .await
    .expect("sell order must be relisted Pending");
    assert_eq!(alice_final.id, alice_order_id, "relisted under the same id");
    assert_ne!(
        alice_final.amount, alice_eth_commitment,
        "order commitment must be rewritten to the remainder commitment"
    );

    // ── Payout NOTES exist in the pool tree ──
    assert!(
        bob.get_note_by_cm(&bob_outcome.recv.cm)
            .await
            .expect("bob note lookup")
            >= 0,
        "bob's payout note must be in the pool tree"
    );
    assert!(
        alice
            .get_note_by_cm(&alice_outcome.recv.cm)
            .await
            .expect("alice note lookup")
            >= 0,
        "alice's payout note must be in the pool tree"
    );
    let alice_eth = alice
        .get_account(&alice_pubkey, TOKEN1)
        .await
        .expect("alice ETH account");
    assert!(
        alice_eth
            .cash
            .iter()
            .any(|c| c.id == rem.locked.cash_id && c.status == CASH_LOCKED),
        "alice must hold the relisted Locked ETH remainder cash"
    );

    // Scratch cleanup (the chain process is killed by ChainGuard on drop).
    let _ = fs::remove_dir_all(&sessions_root);
    let _ = fs::remove_file(&cfg_path);
}
