services:
  chain:
    build:
      context: ./chain
    ports:
      - "7999:7999"
      - "8999:8999"
      - "8887:8887"
    volumes:
      - ~/.invisibook/chain/data:/app/data
    restart: unless-stopped
