//go:build cozk2p

package test

import (
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/invisibook-lab/invisibook/core"
)

// cozk2pE2eFixture is the subset of `dump_settle2p_fixture` output this test
// needs (the full schema is documented in core/cozk2p_layout_test.go).
// Locked-only model: the proved statement covers the two locked collateral
// commitments plus the public price and A's side.
type cozk2pE2eFixture struct {
	Cmp        int    `json:"cmp"`
	LockedAHex string `json:"locked_a_hex"`
	LockedBHex string `json:"locked_b_hex"`
	Price      uint64 `json:"price"`
	AIsSeller  bool   `json:"a_is_seller"`
	ProofHex   string `json:"proof_hex"`
	VKPath     string `json:"vk_path"`
}

// TestCoZk2pSettleRealProofOnChain is the full-depth e2e of the 2-party
// path: a REAL collaboratively generated PLONK π_cmp travels through
// SubmitCompareCoZk2p on a REAL running chain whose PLONK verification is
// ON (config generated from the fixture: the genesis order commitments are
// exactly the ones the two SPDZ parties proved against). A tampered proof
// must leave state untouched; the genuine proof must record the comparison,
// after which the settle writings (proof-skipped in this config) complete
// the lifecycle.
//
// Requires `./invisibook` built with `-tags cozk2p` and the fixture from
// `dump_settle2p_fixture` (see `make test-e2e-cozk2p`).
func TestCoZk2pSettleRealProofOnChain(t *testing.T) {
	raw, err := os.ReadFile("/tmp/settle_cozk2p_fixture.json")
	if err != nil {
		t.Skip("fixture not found — run `make dump-cozk2p-fixture` first")
	}
	var fx cozk2pE2eFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("decoding fixture: %v", err)
	}
	if fx.VKPath == "" {
		t.Fatal("fixture has no vk_path — regenerate it passing --vk-out")
	}
	if fx.Cmp != 1 {
		t.Fatalf("this test assumes the sample trade's cmp=1, got %d", fx.Cmp)
	}
	if !fx.AIsSeller {
		t.Fatalf("this test assumes the sample trade's A side sells")
	}
	if fx.Price == 0 {
		t.Fatal("fixture has no price — regenerate it for the locked-only model")
	}

	alicePriv, alicePubkey := deriveKeypair(t, aliceDerivedSeedHex)
	bobPriv, bobPubkey := deriveKeypair(t, bobDerivedSeedHex)

	// --- Generate a chain config bound to the fixture: PLONK verification
	// ON; the settle VK paths stay empty so the post-compare writings run
	// proof-skipped. No genesis state is needed: v2 orders spend notes by
	// nullifier and test mode derives them from tag strings. ---
	cfg := fmt.Sprintf(`# Generated by TestCoZk2pSettleRealProofOnChain — do not commit.
[orderbook]
db_path = "data/orders.db"
settle_cozk2p_vk_path = %q
require_proofs = false

[account]
db_path = "data/accounts.db"
require_proofs = false
`, fx.VKPath)
	cfgPath := filepath.Join(t.TempDir(), "core_cozk2p_e2e.toml")
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o644); err != nil {
		t.Fatalf("writing generated config: %v", err)
	}

	// --- Start a fresh chain on that config ---
	exec.Command("bash", "-c", "lsof -ti:7999 -ti:8999 -ti:8887 | xargs kill -9 2>/dev/null").Run()
	time.Sleep(1 * time.Second)
	chainDir := ".."
	os.RemoveAll(chainDir + "/data")
	cmd := exec.Command("./invisibook", "--core-config", cfgPath)
	cmd.Dir = chainDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		t.Fatalf("failed to start chain: %v", err)
	}
	defer func() {
		cmd.Process.Kill()
		cmd.Wait()
	}()
	time.Sleep(6 * time.Second)

	// --- Send both orders carrying the fixture's locked commitments; alice
	// first so her sell is the maker (order A / circuit a-side) ---
	sellReq := signedSendOrder(alicePriv, core.Sell, "ETH", "USDT",
		fx.Price, fx.LockedAHex, alicePubkey, []string{"alice-eth-note"})
	sellOrderID := sellReq.ID
	if err := wrCall("orderbook", "SendOrder", sellReq); err != nil {
		t.Fatalf("SendOrder (sell) failed: %v", err)
	}
	waitBlock()

	buyReq := signedSendOrder(bobPriv, core.Buy, "ETH", "USDT",
		fx.Price, fx.LockedBHex, bobPubkey, []string{"bob-usdt-note"})
	buyOrderID := buyReq.ID
	if err := wrCall("orderbook", "SendOrder", buyReq); err != nil {
		t.Fatalf("SendOrder (buy) failed: %v", err)
	}
	waitBlock()

	if st := queryOrders(t, sellOrderID)[0].Status; st != 1 {
		t.Fatalf("expected sell order Matched(1), got %d", st)
	}

	// --- Compare request straight from the fixture ---
	req := &core.CompareRequest{
		OrderAID: sellOrderID,
		OrderBID: buyOrderID,
		Cmp:      fx.Cmp,
		ZkProof:  fx.ProofHex,
	}

	// Negative: one flipped proof byte must fail PLONK verification
	// on-chain and leave the pair Matched.
	badReq := *req
	badReq.ZkProof = bumpHexByte(fx.ProofHex)
	msg := core.CoZk2pCompareMessage(&badReq)
	badReq.SigA = hex.EncodeToString(ed25519.Sign(alicePriv, msg))
	badReq.SigB = hex.EncodeToString(ed25519.Sign(bobPriv, msg))
	if err := wrCall("orderbook", "SubmitCompareCoZk2p", &badReq); err != nil {
		t.Fatalf("submitting tampered-proof compare failed at HTTP level: %v", err)
	}
	waitBlock()
	if st := queryOrders(t, sellOrderID)[0].Status; st != 1 {
		t.Fatalf("tampered proof must be rejected: sell order moved to %d", st)
	}

	// Happy path: the genuine collaborative proof records the comparison.
	msg = core.CoZk2pCompareMessage(req)
	req.SigA = hex.EncodeToString(ed25519.Sign(alicePriv, msg))
	req.SigB = hex.EncodeToString(ed25519.Sign(bobPriv, msg))
	if err := wrCall("orderbook", "SubmitCompareCoZk2p", req); err != nil {
		t.Fatalf("SubmitCompareCoZk2p failed: %v", err)
	}
	waitBlock()
	if st := queryOrders(t, sellOrderID)[0].Status; st != 5 { // Settling
		t.Fatalf("expected sell order Settling(5) after real-proof compare, got %d — was ./invisibook built with -tags cozk2p?", st)
	}

	// --- Complete the lifecycle with the ATOMIC SettlePair (proof-skipped
	// in this config; the mechanics are what's under test here) ---
	smallSig := &core.SettleSmallRequest{
		OrderID:      buyOrderID,
		MatchOrderID: sellOrderID,
		CmNoteOut:    hexCommit(0xC1),
	}
	bLeg := core.SettlePairLeg{
		CmNoteOut: smallSig.CmNoteOut,
		ZkProof:   "test-proof-skip",
		Signature: hex.EncodeToString(
			ed25519.Sign(bobPriv, core.SettleSmallSigMessage(smallSig))),
	}
	largeSig := &core.SettleLargeRequest{
		OrderID:          sellOrderID,
		MatchOrderID:     buyOrderID,
		CmLockedResidual: hexCommit(0xA2),
		CmNoteOut:        hexCommit(0xC2),
	}
	aLeg := core.SettlePairLeg{
		CmNoteOut:        largeSig.CmNoteOut,
		CmLockedResidual: largeSig.CmLockedResidual,
		ZkProof:          "test-proof-skip",
		Signature: hex.EncodeToString(
			ed25519.Sign(alicePriv, core.SettleLargeSigMessage(largeSig))),
	}
	pairReq := &core.SettlePairRequest{
		OrderAID: sellOrderID,
		OrderBID: buyOrderID,
		A:        aLeg,
		B:        bLeg,
	}
	if err := wrCall("orderbook", "SettlePair", pairReq); err != nil {
		t.Fatalf("SettlePair failed: %v", err)
	}
	waitBlock()
	if st := queryOrders(t, buyOrderID)[0].Status; st != 2 { // Done
		t.Fatalf("expected buy order Done(2), got %d", st)
	}
	if st := queryOrders(t, sellOrderID)[0].Status; st != 0 { // Pending (relisted)
		t.Fatalf("expected relisted sell order Pending(0), got %d", st)
	}
	if getNoteByCm(t, bLeg.CmNoteOut) < 0 || getNoteByCm(t, aLeg.CmNoteOut) < 0 {
		t.Fatal("both payout notes must be in the pool tree")
	}

	t.Log("=== 2-party real-proof comparison + settlement lifecycle verified on-chain ===")
}

// bumpHexByte flips the last hex nibble of `s`, keeping it valid hex.
func bumpHexByte(s string) string {
	if s == "" {
		return "0"
	}
	next := byte('0')
	if s[len(s)-1] == '0' {
		next = '1'
	}
	return s[:len(s)-1] + string(next)
}
