//go:build cozk2p

package test

import (
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/invisibook-lab/invisibook/core"
)

// cozk2pE2eFixture is the subset of `dump_settle2p_fixture` output this test
// needs (the full schema is documented in core/cozk2p_layout_test.go).
type cozk2pE2eFixture struct {
	Price                   uint64    `json:"price"`
	Cmp                     int       `json:"cmp"`
	OrderACommitmentHex     string    `json:"order_a_commitment_hex"`
	OrderBCommitmentHex     string    `json:"order_b_commitment_hex"`
	LockedAHashesHex        [2]string `json:"locked_a_hashes_hex"`
	LockedBHashesHex        [2]string `json:"locked_b_hashes_hex"`
	NewOrderACommitmentHex  string    `json:"new_order_a_commitment_hex"`
	NewOrderBCommitmentHex  string    `json:"new_order_b_commitment_hex"`
	NewLockedACommitmentHex string    `json:"new_locked_a_commitment_hex"`
	NewLockedBCommitmentHex string    `json:"new_locked_b_commitment_hex"`
	RecvACommitmentHex      string    `json:"recv_a_commitment_hex"`
	RecvBCommitmentHex      string    `json:"recv_b_commitment_hex"`
	ProofHex                string    `json:"proof_hex"`
	VKPath                  string    `json:"vk_path"`
}

// TestCoZk2pSettleRealProofOnChain is the full-depth e2e of the 2-party
// path: a REAL collaboratively generated PLONK proof travels through
// SettleOrdersCoZk2p on a REAL running chain whose PLONK verification is ON
// (config generated from the fixture: genesis collateral equals the
// fixture's locked commitments, so the on-chain statement the writing
// rebuilds is exactly the one the two SPDZ parties proved). A tampered
// proof must leave state untouched; the genuine proof must settle.
//
// Requires `./invisibook` built with `-tags cozk2p` and the fixture from
// `dump_settle2p_fixture` (see `make test-e2e-cozk2p`).
func TestCoZk2pSettleRealProofOnChain(t *testing.T) {
	raw, err := os.ReadFile("/tmp/settle_cozk2p_fixture.json")
	if err != nil {
		t.Skip("fixture not found — run `make dump-cozk2p-fixture` first")
	}
	var fx cozk2pE2eFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("decoding fixture: %v", err)
	}
	if fx.VKPath == "" {
		t.Fatal("fixture has no vk_path — regenerate it passing --vk-out")
	}
	if fx.Cmp != 1 {
		t.Fatalf("this test assumes the sample trade's cmp=1, got %d", fx.Cmp)
	}

	alicePriv, alicePubkey := deriveKeypair(t, aliceDerivedSeedHex)
	bobPriv, bobPubkey := deriveKeypair(t, bobDerivedSeedHex)

	// --- Generate a chain config bound to the fixture: PLONK verification
	// ON, genesis collateral = the commitments the proof opens ---
	aliceCashID := cashID(alicePubkey, "ETH", fx.LockedAHashesHex[0])
	bobCashID := cashID(bobPubkey, "USDT", fx.LockedBHashesHex[0])
	cfg := fmt.Sprintf(`# Generated by TestCoZk2pSettleRealProofOnChain — do not commit.
[orderbook]
db_path = "data/orders.db"
settle_cozk2p_vk_path = %q

[account]
db_path = "data/accounts.db"

[[account.genesis_cash]]
id     = %q
pubkey = %q
token  = "ETH"
amount = %q

[[account.genesis_cash]]
id     = %q
pubkey = %q
token  = "USDT"
amount = %q
`, fx.VKPath,
		aliceCashID, alicePubkey, fx.LockedAHashesHex[0],
		bobCashID, bobPubkey, fx.LockedBHashesHex[0])
	cfgPath := filepath.Join(t.TempDir(), "core_cozk2p_e2e.toml")
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o644); err != nil {
		t.Fatalf("writing generated config: %v", err)
	}

	// --- Start a fresh chain on that config ---
	exec.Command("bash", "-c", "lsof -ti:7999 -ti:8999 -ti:8887 | xargs kill -9 2>/dev/null").Run()
	time.Sleep(1 * time.Second)
	chainDir := ".."
	os.RemoveAll(chainDir + "/data")
	cmd := exec.Command("./invisibook", "--core-config", cfgPath)
	cmd.Dir = chainDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		t.Fatalf("failed to start chain: %v", err)
	}
	defer func() {
		cmd.Process.Kill()
		cmd.Wait()
	}()
	time.Sleep(6 * time.Second)

	// --- Send both orders at the fixture's execution price; alice first so
	// her sell is the maker (order A / circuit a-side, the seller) ---
	sellReq := signedSendOrder(alicePriv, core.Sell, "ETH", "USDT",
		fx.Price, fx.OrderACommitmentHex, alicePubkey, []string{aliceCashID})
	sellOrderID := sellReq.ID
	if err := wrCall("orderbook", "SendOrder", sellReq); err != nil {
		t.Fatalf("SendOrder (sell) failed: %v", err)
	}
	waitBlock()

	buyReq := signedSendOrder(bobPriv, core.Buy, "ETH", "USDT",
		fx.Price, fx.OrderBCommitmentHex, bobPubkey, []string{bobCashID})
	buyOrderID := buyReq.ID
	if err := wrCall("orderbook", "SendOrder", buyReq); err != nil {
		t.Fatalf("SendOrder (buy) failed: %v", err)
	}
	waitBlock()

	if st := queryOrders(t, sellOrderID)[0].Status; st != 1 {
		t.Fatalf("expected sell order Matched(1), got %d", st)
	}

	// --- Settlement request straight from the fixture ---
	req := &core.CoZkSettleRequest{
		OrderAID:             sellOrderID,
		OrderBID:             buyOrderID,
		Cmp:                  fx.Cmp,
		NewOrderACommitment:  fx.NewOrderACommitmentHex,
		NewOrderBCommitment:  fx.NewOrderBCommitmentHex,
		NewLockedACommitment: fx.NewLockedACommitmentHex,
		NewLockedBCommitment: fx.NewLockedBCommitmentHex,
		RecvACommitment:      fx.RecvACommitmentHex,
		RecvBCommitment:      fx.RecvBCommitmentHex,
		ZkProof:              fx.ProofHex,
	}

	// --- Negative case: one flipped proof byte must fail PLONK
	// verification on-chain and leave the pair Matched ---
	badReq := *req
	badReq.ZkProof = bumpHexByte(fx.ProofHex)
	msg := core.CoZk2pSettleMessage(&badReq)
	badReq.SigA = hex.EncodeToString(ed25519.Sign(alicePriv, msg))
	badReq.SigB = hex.EncodeToString(ed25519.Sign(bobPriv, msg))
	if err := wrCall("orderbook", "SettleOrdersCoZk2p", &badReq); err != nil {
		t.Fatalf("submitting tampered-proof settle failed at HTTP level: %v", err)
	}
	waitBlock()
	if st := queryOrders(t, sellOrderID)[0].Status; st != 1 {
		t.Fatalf("tampered proof must be rejected: sell order moved to %d", st)
	}

	// --- Happy path: the genuine collaborative proof settles ---
	msg = core.CoZk2pSettleMessage(req)
	req.SigA = hex.EncodeToString(ed25519.Sign(alicePriv, msg))
	req.SigB = hex.EncodeToString(ed25519.Sign(bobPriv, msg))
	if err := wrCall("orderbook", "SettleOrdersCoZk2p", req); err != nil {
		t.Fatalf("SettleOrdersCoZk2p failed: %v", err)
	}
	waitBlock()

	if st := queryOrders(t, buyOrderID)[0].Status; st != 2 { // Done
		t.Fatalf("expected buy order Done(2), got %d — was ./invisibook built with -tags cozk2p?", st)
	}
	sellAfter := queryOrders(t, sellOrderID)[0]
	if sellAfter.Status != 0 { // Pending (relisted remainder)
		t.Fatalf("expected relisted sell order Pending(0), got %d", sellAfter.Status)
	}
	if sellAfter.Amount != fx.NewOrderACommitmentHex {
		t.Fatalf("relisted order amount = %s, want %s", sellAfter.Amount, fx.NewOrderACommitmentHex)
	}
	foundRecvB := false
	for _, c := range getAccount(t, bobPubkey, "ETH") {
		if c.Amount == fx.RecvBCommitmentHex && c.Status == 0 {
			foundRecvB = true
		}
	}
	if !foundRecvB {
		t.Fatalf("expected bob to hold an Active ETH recv cash with amount %s", fx.RecvBCommitmentHex)
	}

	t.Log("=== 2-party real-proof settlement verified on-chain ===")
}

// bumpHexByte flips the last hex nibble of `s`, keeping it valid hex.
func bumpHexByte(s string) string {
	if s == "" {
		return "0"
	}
	next := byte('0')
	if s[len(s)-1] == '0' {
		next = '1'
	}
	return s[:len(s)-1] + string(next)
}
