[package]
name = "mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-mpc = { git = "https://github.com/invisibook-lab/ark-mpc", features = ["test_helpers"] }
ark-bn254 = "0.4"
ark-ec = "0.4"
ark-ff = "0.4"
ark-std = "0.4"
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
light-poseidon = "0.2"
num-bigint = "0.4"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
rand = "0.8"

[[example]]
name = "party"
path = "examples/party.rs"

[[bench]]
name = "compare"
harness = false
