[package]
name = "invisibook-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.7"
hex = "0.4"
invisibook-lib = { path = "../../lib/chain" }
tokio = { version = "1", features = ["time"] }
serde_json = "1"

[target.'cfg(not(target_os = "android"))'.dependencies]
zk = { path = "../../lib/zk" }
mpc = { path = "../../lib/mpc" }
sha2 = "0.10"
num-bigint = "0.4"
x25519-dalek = { version = "2", features = ["static_secrets"] }
ed25519-dalek = "2"
curve25519-dalek = "4"
rand = "0.9"
