[package]
name = "invisibook-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.7"
dirs = "6"
hex = "0.4"
invisibook-lib = { path = "../../lib/chain" }
tokio = { version = "1", features = ["time"] }
serde_json = "1"

[target.'cfg(not(target_os = "android"))'.dependencies]
zk = { path = "../../lib/zk" }
