[package]
name = "zk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
ark-bn254 = "0.5"
ark-crypto-primitives = { version = "0.5", features = ["snark"] }
ark-ec = "0.5"
ark-ff = "0.5"
ark-groth16 = "0.5"
ark-relations = "0.5"
ark-serialize = "0.5"
ark-std = { version = "0.5", features = ["std"] }
byteorder = "1.5"
light-poseidon = "0.4"
num-bigint = "0.4"
r1cs-file = "0.3"
rand = { version = "0.8", features = ["std", "std_rng"] }
serde_json = "1.0"
tempfile = "3.23"
wtns-file = "0.1"
